#!/usr/bin/env python
"""Could rttpf have expressed the correction the camera model learned?

"The lens is underfit by rttpf" hides two very different claims:

  MISFIT      rttpf's functional form can describe this lens, but the delivered
              coefficients are wrong -- a better calibration would have got the gain for
              free, with no new model.
  INEXPRESSIVE no choice of (fx, k1..k4) reproduces the corrected mapping -- the residual
              lives outside rttpf's span and only a richer camera model can reach it.

The test: the learned residual moves each pixel radius r from angle theta to theta + dtheta.
So the corrected forward map passes through the samples (theta_i + dtheta_i, r_i). Fit the
rttpf radial form to those samples; whatever it cannot fit is the inexpressive part.

  r(theta) = fx * theta * (1 + k1 t^2 + k2 t^4 + k3 t^6 + k4 t^8)

is LINEAR in (fx, fx*k1, ... fx*k4) over the basis [t, t^3, t^5, t^7, t^9], so this is an
exact least-squares question, not an optimisation with a local minimum.

Control: fitting the SAME basis to the UNcorrected samples must return ~0 residual, because
those samples were generated by exactly this form. If it does not, the test is broken.

The non-central term is deliberately excluded here: `z(theta)` moves the ray ORIGIN, so no
central model of any order can express it by construction. Its size is quantified separately
in scripts/analysis/optics.py.

usage: python scripts/analysis/residual_expressible.py
"""

import json
import os
import sys

import numpy as np
import pycolmap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import calib_consistency as C  # noqa: E402

BASIS = [1, 3, 5, 7, 9]  # * odd powers of theta: exactly rttpf's radial span


def fit_rttpf(theta, r):
    """Least-squares fit of the rttpf radial form; returns (predicted r, rms residual px)."""
    design = np.stack([theta**p for p in BASIS], axis=1)
    coefficients, *_ = np.linalg.lstsq(design, r, rcond=None)
    predicted = design @ coefficients
    return predicted, float(np.sqrt(np.mean((predicted - r) ** 2)))


def analyse(name, scenes, sparse_of, run_of, uid):
    fits = []
    for scene in scenes:
        sparse = sparse_of(scene)
        if not os.path.isdir(sparse):
            continue
        rec = pycolmap.Reconstruction(sparse)
        if uid not in rec.cameras:
            continue
        params = list(rec.cameras[uid].params)
        grid = np.linspace(0.0, np.pi / 2, 4000)
        radii = C.r_of_theta(params[0], C.radial_poly(params), grid)
        fold = np.argmax(np.diff(radii) <= 0) if (np.diff(radii) <= 0).any() else len(grid) - 1
        fits.append({"scene": scene, "params": params, "theta_max": grid[fold],
                     "r_max": radii[fold]})
    if not fits:
        return None

    r_px = C.GRID * min(f["r_max"] for f in fits)
    thetas, deltas = [], []
    for f in fits:
        theta = C.theta_of_r(f["params"][0], C.radial_poly(f["params"]), r_px, f["theta_max"])
        d = C.learned_dtheta(run_of(f["scene"]), uid, theta)
        if d is None:
            return None
        thetas.append(theta)
        deltas.append(d)
    theta = np.stack(thetas).mean(0)          # * the common lens, as calibrated
    shared = np.stack(deltas).mean(0)         # * the correction every scene agrees on
    # * All pixel figures at the resolution the run was TRAINED at (gray: -r 4), not at
    # * sensor resolution -- those are the pixels the renderer samples. The percentage is
    # * a ratio and so is unaffected; the absolute px are 4x smaller than COLMAP's frame.
    down = C.run_downsampling(run_of(fits[0]["scene"]))
    scale = C.plate_scale(np.mean([f["params"][0] for f in fits]),
                          C.radial_poly(fits[0]["params"]), theta) / down

    # * Control: the uncorrected curve must be exactly representable.
    _, control_rms = fit_rttpf(theta, r_px / down)
    # * The corrected curve: same radii, angles shifted by the learned residual.
    _, corrected_rms = fit_rttpf(theta + shared, r_px / down)

    total = float(np.abs(shared * scale).max())
    print(f"\n### {name}  (uid {uid}, {len(fits)} scenes)")
    print(f"  correction the model learned (shared)      : {total:.3f} px max")
    print(f"  control -- rttpf refit of the RAW curve    : {control_rms:.4f} px rms "
          f"({'OK' if control_rms < 0.02 else 'TEST BROKEN'})")
    print(f"  rttpf refit of the CORRECTED curve         : {corrected_rms:.4f} px rms")
    inexpressive = max(corrected_rms - control_rms, 0.0)
    print(f"  => absorbable by re-fitting rttpf          : "
          f"{100 * (1 - inexpressive / max(total, 1e-9)):.1f} % of it")
    print(f"  => OUTSIDE rttpf's span                    : {inexpressive:.4f} px rms")
    return {"name": name, "uid": uid, "total_px": total,
            "control_rms_px": control_rms, "corrected_rms_px": corrected_rms,
            "inexpressive_px": inexpressive}


def main():
    out = [analyse("myscenes (one lens, 7 independent COLMAP fits)", list(C.MYSCENES),
                   lambda s: f"{C.MY_ROOT}/{C.MYSCENES[s]}/distorted/sparse/0",
                   lambda s: C.MY_RUNS.format(scene=s), 1)]
    for uid in (1, 2):
        out.append(analyse(f"FullCircle refit_rttpf (lens {uid})", C.FC,
                           lambda s: f"{C.FC_ROOT}/{s}/distorted/sparse/0",
                           lambda s: C.FC_RUNS.format(scene=s), uid))
    dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), "residual_expressible.json")
    with open(dest, "w") as handle:
        json.dump([o for o in out if o], handle, indent=1)
    print(f"\nwrote {dest}")


if __name__ == "__main__":
    main()
